name: clone_voice
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+8

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.3.2
  #provider
  flutter_mobx: ^2.0.6+5
  mobx: ^2.2.0
  flutter_screenutil: ^5.8.4
  cached_network_image: ^3.2.3
  shared_preferences: ^2.1.0
  flutter_cache_manager: ^3.3.1
  audio_waveforms: ^1.0.4
  siri_wave: ^1.0.1
  metaballs: ^1.5.0
  jumping_dot: ^0.0.6
  share_plus: ^7.1.0
  path_provider: ^2.1.0
  fluttertoast: ^8.2.2
  url_launcher: ^6.1.12
  purchases_flutter: ^5.6.2
  freerasp: ^6.2.0
  assets_audio_player: ^3.1.0
  shimmer: ^3.0.0
  onesignal_flutter: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mobx_codegen: ^2.1.1
  build_runner: ^2.3.3
  json_serializable: ^6.6.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/voices/
