import 'package:flutter/material.dart';

class AppConstants {
  //TODO: add langs
  static const supportedLocales = [
    Locale('ar', ''),
    Locale('en', ''),
    Locale('cs', ''),
    Locale('da', ''),
    Locale('en', ''),
    Locale('de', ''),
    Locale('el', ''),
    Locale('en', ''),
    Locale('es', ''),
    Locale('fi', ''),
    Locale('fr', ''),
    Locale('hi', ''),
    Locale('hr', ''),
    Locale('id', ''),
    Locale('it', ''),
    Locale('ja', ''),
    Locale('kr', ''),
    Locale('ms', ''),
    Locale('fr', ''),
    Locale('nl', ''),
    Locale('pl', ''),
    Locale('pt', 'pt'),
    Locale('pt', 'BR'),
    Locale('ro', ''),
    Locale('ru', ''),
    Locale('pt', ''),
    Locale('sk', ''),
    Locale('sv', ''),
    Locale('ta', ''),
    Locale('pt', ''),
    Locale('tl', ''),
    Locale('tr', ''),
    Locale('ur', ''),
    Locale('zh', ''),
  ];

  static const supportedLangs = <String>[
    'ar',
    'en',
    'cs',
    'da',
    'en',
    'de',
    'el',
    'en',
    'es',
    'fi',
    'fr',
    'hi',
    'hr',
    'id',
    'it',
    'ja',
    'kr',
    'ms',
    'fr',
    'nl',
    'pl',
    'ro',
    'ru',
    'pt',
    'pt_BR',
    'sk',
    'sv',
    'ta',
    'pt',
    'tl',
    'tr',
    'ur',
    'zh',
  ];
}
